name: Conda Atomic Simulation Environment
channels:
  - conda-forge
dependencies:
  - psutil
  - toolz
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - pip
  - matplotlib
  - numpy
  - scipy
  - ase
  - nglview
  - phonopy
  - lammps
  - jupyter_contrib_nbextensions
  - pip:
    - jupyterlab_latex
