name: Conda Atomic Simulation Environment
channels:
  - conda-forge
dependencies:
  - psutil
  - toolz
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - matplotlib
  - numpy
  - scipy
  - ase
  - nglview
  - phonopy
  - lammps
  - jupyter_contrib_nbextensions
  - dvipng
  - ghostscript
  - texlive-fonts-recommended
  - texlive-generic-recommended
  - texlive-latex-base
  - texlive-latex-extra
  - texlive-latex-recommended
  - texlive-publishers
  - texlive-science
  - texlive-xetex
  - cm-super
